version: '2'
services:
  dokuwiki:
    build: .
    image: docker-hub.deyiyc.com:5000/kuilian/dokuwiki:latest
    ports:
      - 8004:80
    environment:
      - DIR=wiki
    volumes:
      - ./.data:/opt/data
    
